name: gate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: check style
        uses: actions-rust-lang/rustfmt@v1

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: lint
        run: cargo clippy

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: run unit tests
        run: cargo test

  benchmark:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: restore cache
      uses: actions/cache@v4
      with:
        path: target/criterion
        key: bench-${{ runner.os }}
    - name: benchmark
      run: cargo bench --bench traquer -- --noplot
